services:
  # Zipkin para coleta de traces
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - otel-network

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - zipkin
    networks:
      - otel-network

  # Serviço A - Input Service
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    container_name: service-a
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - SERVICE_B_URL=http://service-b:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=service-a
      - OTEL_SERVICE_VERSION=1.0.0
    depends_on:
      - otel-collector
      - service-b
    networks:
      - otel-network

  # Serviço B - Orchestration Service  
  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    container_name: service-b
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc 
      - OTEL_SERVICE_NAME=service-b
      - OTEL_SERVICE_VERSION=1.0.0
      - WEATHER_API_KEY=ad43e5d744964ababd411426252107
    depends_on:
      - otel-collector
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge